version: '3.3'

services:
    node-server:
        build:
            context: .
        ports:
            - "80:80"
        volumes:
            - ./code:/code
        command: sh -c "tail -F /dev/null"
        working_dir: /code